title: "🚀 WAF Deployment"

variableGroups:
  - title: "Compartment"
    variables:
      - create_compartment
      - compartment_name
      - compartment_id

  - title: "Network"
    variables:
      - create_network
      - vcn_cidr
      - subnet_cidr
      - vcn_id
      - subnet_id

  - title: "Instance"
    variables:
      - create_instance
      - instance_name
      - instance_count
      - instance_private_ip
      - existing_instance_ips

  - title: "Load Balancer"
    variables:
      - create_lb
      - lb_name
      - lb_shape

variables:

  create_compartment:
    type: boolean
    title: "Create New Compartment?"
    default: false

  compartment_name:
    type: string
    title: "New Compartment Name"
    visible:
      eq:
        create_compartment: true

  compartment_id:
    type: string
    title: "Existing Compartment OCID"
    visible:
      eq:
        create_compartment: false

  create_network:
    type: boolean
    title: "Create Network?"
    default: true

  vcn_cidr:
    type: string
    default: "10.0.0.0/16"
    visible:
      eq:
        create_network: true

  subnet_cidr:
    type: string
    default: "10.0.1.0/24"
    visible:
      eq:
        create_network: true

  vcn_id:
    type: string
    title: "Existing VCN OCID"
    visible:
      eq:
        create_network: false

  subnet_id:
    type: string
    title: "Existing Subnet OCID"
    visible:
      eq:
        create_network: false

  create_instance:
    type: boolean
    title: "Create Instance?"
    default: true

  instance_name:
    type: string
    visible:
      eq:
        create_instance: true

  instance_count:
    type: number
    default: 1
    visible:
      eq:
        create_instance: true

  instance_private_ip:
    type: string
    visible:
      eq:
        create_instance: true

  existing_instance_ips:
    type: string
    title: "Existing Instance IPs"
    visible:
      eq:
        create_instance: false

  create_lb:
    type: boolean
    title: "Create Load Balancer?"
    default: true

  lb_name:
    type: string

  lb_shape:
    type: enum
    enum:
      - flexible
      - 100Mbps
      - 400Mbps
    default: flexible
